import React from "react";
import Header from "@/components/layout/header/Header";
import { Metadata } from "next";
import { getServerSession } from "next-auth";
import { authOption } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Education App | Add Course",
  description: "Generated by create next app",
};

export default async function AddCourseLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOption);
  if (!session) redirect("/");
  return (
    <>
      <Header title="Be a Mentor" />
      {children}
    </>
  );
}
