import React from "react";
import Header from "@/components/layout/header/Header";
import { Metadata } from "next";
import BottomNavigation from "@/components/layout/bottomNavigation/BottomNavigation";

export const metadata: Metadata = {
  title: "Education App | Courses",
  description: "Generated by create next app",
};

export default async function CoursesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header title="Courses" />
      {children}
      <BottomNavigation />
    </>
  );
}
