import type { Metadata } from "next";
import "./globals.css";
import NextAuthProvider from "@/providers/NextAuthProvider";

export const metadata: Metadata = {
  title: "Education App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="max-w-[500px] my-0 mx-auto min-h-[100vh]">
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
