import React from "react";
import { Metadata } from "next";
import Header from "@/components/layout/header/Header";
import BottomNavigation from "@/components/layout/bottomNavigation/BottomNavigation";

export const metadata: Metadata = {
  title: "Education App | Profile",
  description: "Generated by create next app",
};

export default function ProfileLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Header title="Profile" />
      {children}
      <BottomNavigation />
    </div>
  );
}
